### ISSUE TITLE
Gambas Setup

### ISSUE THREAD

**Issue by xvxx** [Lartu/OpenNapkin#1]
Hi, this looks great! And Gambas is very interesting. Big VB fan right here!

I'm trying to get it running but I'm having some trouble. Is the gambas runtime package all you have installed? I think I'm missing a few packages and can't find them.

### running the binary

I installed `gambas3-runtime` and got this error running the `OpenNapkin` binary:

> gbr3: unable to load component: gb.image

So I installed `gambas3-gb-image` and ran it again, this time:

> gbr3: unable to load component: gb.qt4

I don't see any matching packages in `apt`. Do I need to install Qt separately?

----

### building from source

I googled and ended up just installing all of Gambas:

> sudo apt install gambas

It installed the app, but didn't fix the command line error. When I try to open the app's git repo in the Gambas program, I get this error in a popup window:

> CComponent.Load.624
>
> 'UserControl' class is missing in gb.form component exported classes.

Any advice would be appreciated!

PS I setup this tiny little LDPL Gopher page:

gopher://phkt.io/1/ldpl

**Comment by Lartu** [comment]
Thank you! I'm sorry you are having problems with this, I've only used Gambas for a few hours and I don't really know its ins an outs very well.

While the first error you mention (*gbr3: unable to load component: gb.qt4*) seems to be dependency releated (I really thought you would just need the Gambas Runtime), the second one apparently (as far as I could find) is something installation-releated. What Gambas3 version do you have? I was using 3.14, maybe that means something.

All that said, Gambas sockets don't seem to work fine and OpenNapkin ends up loading just a portion of a gophersite now and then. Taking all this into account, I'm just thinking in porting OpenNapking to LDPL + LDPL-GTK and kill two birds with one stone.

**Comment by Lartu** [comment]
(Or plain good old C++)

**Comment by Lartu** [comment]
(Or Lazarus / FreePascal!)

BTW I forgot to try your LDPL gopherpage! It doesn't work fine with OpenNapkin with that 1/ in the address (I still have some Gopher protocol reading to do), but if I remove it the site loads wonderfully!  I love it (but I love it more in Gild that loads it better haha).

**Comment by xvxx** [comment]
Oh great, I installed `3.12.2-1` through `apt install`, let me try upgrading to 3.14/pi and I'll try again.

An LDPL GUI client would be really nice. I've been meaning to play with your GTK library...

For the socket though, you probably need to keep reading in a loop until the connection closes or you get 0 bytes back. You won't always get the entire gopher response body in one call to `read()`. I have to do this in GILD and phetch too. It's because the Gopher protocol is so (too) simple.

I want to try and get the LDPL man page into Gopher eventually, I think that would be some high quality content. 

The `/1/` is a convention gopher clients use because the gopher protocol is too simple, there's no way to tell what kind of content you're going to get back so they stick the item type (`0` or `1`) into the URL so the client knows what to expect. It's pretty strange, I think it'd be better to just assume a MENU by default but I'm not sure what the majority of clients support.
